#!/bin/sh

LSEP=
LSEPE=
RSEP=
RSEPE=

CLOCK=⌚
CALENDAR=☼
MUSIC=♫
BATTERY=B

WIDTH=${1}

SMALL=80
MEDIUM=140

if [ "$WIDTH" -gt "$MEDIUM" ]; then
  MPD="#[fg=colour252,bg=default,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $MUSIC $(amixer sget Master | grep -E -o '[0-9]+%' | sort -r | head -n 1)"
  date_colour='colour252'
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
  BATT="#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $BATTERY $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}')"
fi
DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$RSEP#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] $CALENDAR $(date +'%D')"
TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$RSEPE#[fg=colour252,bg=colour236,bold,noitalics,nounderscore] $CLOCK $(date +'%H:%M')"

echo "$MPD $DATE $TIME $BATT " | sed 's/ *$/ /g'
